# Generated by Django 5.2.14 on 2026-05-13 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('status_coordenador', models.CharField(choices=[('pendente', 'Pendente'), ('validado', 'Validado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atendimentos.atendimento')),
            ],
        ),
    ]
