# Generated by Django 5.2.14 on 2026-05-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('matricula', models.CharField(blank=True, max_length=20)),
                ('perfil', models.CharField(choices=[('aluno', 'Aluno'), ('coordenador', 'Coordenador')], default='aluno', max_length=20)),
                ('periodo', models.CharField(blank=True, max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
