# Generated by Django 5.2.14 on 2026-05-13 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_juridica', models.CharField(choices=[('familia', 'Família'), ('penal', 'Penal'), ('civil', 'Civil'), ('trabalhista', 'Trabalhista'), ('consumidor', 'Consumidor'), ('previdenciario', 'Previdenciário'), ('outros', 'Outros')], max_length=20)),
                ('descricao_caso', models.TextField()),
                ('assinatura_digital', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('encerrado', 'Encerrado')], default='aberto', max_length=20)),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('assistido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.assistido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
